[profile.default]
bytecode_hash = "none"
cbor_metadata = false
evm_version = "cancun"
fs_permissions = [
  { access = "read", path = "./test/staking/fixtures/" },
  { access = "read", path = "./test/withdrawal/fixtures/" },
]
libs = ["lib"]
optimizer = true
optimizer_runs = 10000
out = "out"
src = "src"
via_ir = true

[rpc_endpoints]
base_sepolia    = "https://sepolia.base.org"
exo             = "${EXO_RPC_URL}"
holesky         = "https://ethereum-holesky-rpc.publicnode.com"
localhost       = "http://localhost:8545"
mainnet         = "${ETH_MAINNET_RPC_URL}"
risa_devnet     = "${RISA_DEVNET_RPC_URL}"
sepolia         = "https://ethereum-sepolia-rpc.publicnode.com"
syndicate_frame = "https://rpc-frame.syndicate.io"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
