exclude: vendor|\.pb\.go

repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        args: ["--all", "--check", "--", "--unstable-features"] # nightly Rust required for `imports_granularity` feature
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        args:
          [
            "--workspace",
            "--all-targets",
            "--all-features",
            "--",
            "-D",
            "warnings",
          ]
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-machete
        name: cargo machete
        entry: cargo machete
        language: system
        types: [rust]
        pass_filenames: false
        # it's necessary to specify the arguments one by one to avoid issues with git submodules (particularly inside synd-withdrawals)
        args:
          [
            "Cargo.toml",
            "shared",
            "synd-batch-sequencer",
            "synd-maestro",
            "synd-mchain",
            "synd-translator",
            "synd-verifier",
            "synd-withdrawals/synd-appchain-verifier",
            "synd-withdrawals/synd-proposer-rust",
            "synd-withdrawals/synd-tee-attestation-zk-proofs/aws-nitro",
            "synd-withdrawals/synd-tee-attestation-zk-proofs/sp1/program",
            "test-framework",
          ]
      - id: forge-fmt
        name: forge fmt
        entry: forge fmt
        args: ["--check"]
        language: system
        types: [solidity]
      - id: forge-test-synd-contracts
        name: forge test syndicate contracts
        entry: forge test
        args: ["--root", "synd-contracts"]
        language: system
        types: [solidity]
        files: ^(synd-contracts)/
        pass_filenames: false
      - id: taplo-fmt
        name: Cargo.toml format validation
        entry: taplo fmt
        args: ["--check", "**/Cargo.toml", "--verbose"]
        language: system
        types: [cargo]
        pass_filenames: false
