exclude: vendor|\.pb\.go|contracts/

repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        args: ["--all", "--check", "--", "--unstable-features"] # nightly Rust required for `imports_granularity` feature
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        args:
          [
            "--workspace",
            "--all-targets",
            "--all-features",
            "--",
            "-D",
            "warnings",
          ]
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-machete
        name: cargo machete
        entry: cargo machete
        language: system
        types: [rust]
        pass_filenames: false
      - id: forge-fmt
        name: forge fmt
        entry: forge fmt
        args: ["--check"]
        language: system
        types: [solidity]
      - id: forge-test-metabased-contracts
        name: forge test metabased contracts
        entry: forge test
        args: ["--root", "metabased-contracts"]
        language: system
        types: [solidity]
        files: ^(metabased-contracts)/
        pass_filenames: false
      - id: forge-test-metabased-translator-contracts
        name: forge test metabased translator contracts
        entry: forge test
        args: ["--root", "metabased-translator/contracts"]
        language: system
        types: [solidity]
        files: ^(metabased-translator)/contracts/
        pass_filenames: false
