[config]
default_to_workspace = false
skip_core_tasks = true

[env.RUST_LOG]
value = "warn"

[env.RUST_LOG.condition]
env_not_set = ["RUST_LOG"]

[env.PROFILE]
source = "${CARGO_MAKE_PROFILE}"
default_value = "localnet"

[env.PROFILE.mapping]
development = "localnet"
production = "mainnet"
localnet = "localnet"
devnet = "devnet"
testnet = "testnet"
mainnet = "mainnet"

[tasks.print-sample-command]
cwd = "."
command = "cargo"
args = ["run", "--example", "generate_run_command"]
