# https://taplo.tamasfe.dev/configuration/formatter-options.html

exclude = [
  "synd-contracts/**/Cargo.toml",
  "synd-withdrawals/synd-enclave/nitro/**/Cargo.toml",
]

[formatting]
align_entries        = true
array_trailing_comma = true
column_width         = 80
reorder_arrays       = true
reorder_keys         = true
