# https://taplo.tamasfe.dev/configuration/formatter-options.html

[formatting]
align_entries        = true
array_trailing_comma = true
column_width         = 100
reorder_arrays       = true
reorder_keys         = true
