[package]
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "synd-chain-ingestor"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
alloy             = { workspace = true, features = ["provider-ws"] }
clap              = { workspace = true, features = ["derive", "env"] }
derivative        = { workspace = true }
eyre              = { workspace = true }
fs2               = { workspace = true }
futures-util      = { workspace = true }
humantime         = { workspace = true }
jsonrpsee         = { workspace = true, features = ["server", "ws-client"] }
prometheus-client = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true, features = ["raw_value"] }
shared            = { workspace = true }
tokio             = { workspace = true, features = ["signal"] }
tower             = { workspace = true }
tracing           = { workspace = true }
url               = { workspace = true }

[dev-dependencies]
common         = { workspace = true }
ctor           = { workspace = true }
test-framework = { workspace = true }
test-utils     = { workspace = true }

[lints]
workspace = true
