services:

  mchain:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-mchain:{{ image_tag }}
    container_name: mchain  
    environment:
      - RUST_LOG=warn
      - APPCHAIN_CHAIN_ID={{ chain_id }}
      - DATADIR=/datadir
    ports:
      - "8545"
    volumes:
      - {{ translator_data_mount_point }}:/datadir
    networks:
      - appchains-network

  translator:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-translator:{{ image_tag }}
    container_name: translator
    platform: linux/amd64
    environment:
      - RUST_LOG=warn
      - APPCHAIN_CHAIN_ID={{ chain_id }}
      - SETTLEMENT_WS_URL={{ settlement_rpc_ws_url }}
      - SEQUENCING_WS_URL={{ sequencing_rpc_ws_url }}
      - CONFIG_MANAGER_ADDRESS={{ config_manager_address }}
      - MCHAIN_WS_URL=ws://mchain:8545
    networks:
      - appchains-network
    depends_on:
      - mchain

  nitro:
    image: ghcr.io/syndicateprotocol/nitro/nitro:{{ nitro_image_tag }}
    container_name: nitro
    init: true
    restart: always
    command:
      - "--parent-chain.connection.url=ws://mchain:8545"
      - "--http.api=arb,eth,net,web3,txpool,arbdebug,arbtrace,debug,synd"
      - "--node.dangerous.disable-blob-reader=true"
      - "--node.inbox-reader.check-delay=100ms"
      - "--node.staker.enable=false"
      - "--node.parent-chain-reader.poll-interval=100ms"
      - "--node.parent-chain-reader.old-header-timeout=2540400h"
      - "--execution.parent-chain-reader.old-header-timeout=2540400h"
      - "--execution.caching.archive=true"
      - "--ensure-rollup-deployment=false"
      - "--chain.info-files=/config/chain_info.json"
      - "--metrics"
      - "--log-level=error"
    ports:
      - "8547"
      - "6070"
    volumes:
      - {{ chain_config_file }}:/config/chain_info.json:ro
      - {{ nitro_data_mount_point }}:/home/user/.arbitrum
    depends_on:
      - translator
    networks:
      - appchains-network

networks:
  appchains-network:
    driver: bridge