set shell := ["zsh", "-cu"]

ATT_DOC_PATH := "../../aws-nitro/src/testdata/att_doc_sample_2.hex"
ROOT_CERT_PATH := "../../aws-nitro/src/testdata/aws_nitro_root.pem"

# sp1

sp1-execute:
    cd sp1/script && \
    RUST_LOG=info cargo run --release -- --att-doc={{ATT_DOC_PATH}} --root-cert={{ROOT_CERT_PATH}} --execute

sp1-prove:
    cd sp1/script && \
    RUST_LOG=info cargo run --release -- --att-doc={{ATT_DOC_PATH}} --root-cert={{ROOT_CERT_PATH}} --prove

sp1-generate-vkey:
    cd sp1/script && \
    RUST_LOG=info cargo run --release --bin vkey

sp1-generate-proof-groth16:
    cd sp1/script && \
    RUST_LOG=info cargo run --release --bin evm -- --att-doc={{ATT_DOC_PATH}} --root-cert={{ROOT_CERT_PATH}} --system groth16

sp1-generate-proof-plonk:
    cd sp1/script && \
    RUST_LOG=info cargo run --release --bin evm -- --att-doc={{ATT_DOC_PATH}} --root-cert={{ROOT_CERT_PATH}} --system plonk


# risc0

r0-run:
    cd risc0 && \
    cargo run --release -- --path=../lib/src/certs

