[package]
name = "data-ingestor"
version = "0.1.0"
edition = "2021"

[dependencies]
pre-commit-hooks = "0.3.0"
alloy-provider = "0.8.2"
alloy-pubsub = "0.8.2"
alloy-transport-http = "0.8.2"
reqwest = "0.12.0"
