[package]
description            = "Common test utilities"
edition.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "test-utils"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
eyre               = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
