[package]
name = "slotting"
version.workspace = true
description = "This crate is responsible for slotting source chain blocks into slots for the block-builder."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy = { workspace = true }
common = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt"] }
tracing = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true, features = ["derive"] }


[dev-dependencies]
test-case = { workspace = true }
serial_test = { workspace = true }


[lints]
workspace = true
