[package]
name = "ingestor"
version.workspace = true
description = "Ingestor for metabased-translator."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
pre-commit-hooks = "0.3.0"
alloy = { version = "0.8.3", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
env_logger = "0.10" # Use the latest version
log = "0.4"

[lints]
workspace = true
