[package]
description            = "Ingestor for metabased-translator."
edition.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "ingestor"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
alloy = { workspace = true, features = [] }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
common = { workspace = true }
eyre = { workspace = true }
humantime = { workspace = true }
prometheus-client = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
async-trait    = { workspace = true }
mockall        = { workspace = true }


[lints]
workspace = true
