[package]
name = "ingestor"
version = "0.1.0"
edition = "2021"

[dependencies]
pre-commit-hooks = "0.3.0"
alloy-provider = "0.8.2"
alloy-pubsub = "0.8.2"
alloy-transport= "0.8.1"
reqwest = "0.12.0"
futures-util = "0.3.31"
alloy = "0.8.3"
eyre = "0.6.12"
tokio = "1.42.0"
