[package]
name = "ingestor"
version.workspace = true
description = "Ingestor for metabased-translator."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
pre-commit-hooks = "0.3.0"
alloy = "0.8.3"
eyre = "0.6.12"
tokio = "1.42.0"
