[package]
name = "ingestor"
version.workspace = true
description = "Ingestor for metabased-translator."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
common.workspace = true
eyre = "0.6.12"
alloy = { version = "0.8.3", features = ["full"] }
tokio = { version = "1.42.0", features = ["full", "test-util", "macros"] }
env_logger = "0.10"                                                        # Use the latest version
log = "0.4"
pre-commit-hooks = "0.3.0"

[lints]
workspace = true
