[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
prometheus-client = { workspace = true }
axum = { workspace = true }
tokio ={ workspace = true}
clap = { workspace = true }
thiserror ={ workspace = true}
tracing ={ workspace = true }