[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
clap = { workspace = true }
prometheus-client = { workspace = true }
reqwest = { workspace = true }
tokio ={ workspace = true}
thiserror = { workspace = true}
tracing = { workspace = true }