[package]
edition.workspace      = true
license.workspace      = true
name                   = "metabased-translator"
rust-version.workspace = true
version.workspace      = true

[[bin]]
name = "metabased-translator"
path = "src/main.rs"

[dependencies]
block-builder     = { workspace = true }
clap              = { workspace = true }
common            = { workspace = true }
eyre              = { workspace = true }
ingestor          = { workspace = true }
metrics           = { workspace = true }
prometheus-client = { workspace = true }
slotter           = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true, features = ["signal"] }
tracing           = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
mockall     = { workspace = true }
serial_test = { workspace = true }


[[example]]
name = "generate_run_command"
path = "examples/generate_run_command.rs"
