[package]
name = "metabased-translator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "metabased-translator"
path = "src/main.rs"

[dependencies]
block-builder = {workspace = true}
metrics = { workspace = true}
ingestor = {workspace = true}
slotting = {workspace = true}
common = {workspace = true}
clap = {workspace = true}
tracing = {workspace = true}
tokio = {workspace = true, features = ["signal"]}
eyre = {workspace = true}
thiserror = {workspace = true}
prometheus-client = {workspace = true}

[dev-dependencies]
serial_test = {workspace = true}

[[example]]
name = "generate_run_command"
path = "examples/generate_run_command.rs"