[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
localhost = "http://localhost:8545"
base_sepolia = "https://sepolia.base.org"
syndicate_frame = "https://rpc-frame.syndicate.io"
optimism = "https://mainnet.optimism.io"
metabased_testnet = "${METABASED_TESTNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
