[package]
description            = "Sequencer batcher"
edition.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "batcher"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
alloy      = { workspace = true }
clap       = { workspace = true, features = ["derive", "env"] }
eyre       = { workspace = true }
humantime  = { workspace = true }
serde_json = { workspace = true }
shared     = { workspace = true }
tc-client  = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true, features = ["full"] }
tracing    = { workspace = true }


[dev-dependencies]
mockall = { workspace = true }

[lints]
workspace = true
