[package]
description            = "Sequencer batcher"
edition.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "batcher"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
alloy     = { workspace = true }
clap      = { workspace = true, features = ["derive", "env"] }
eyre      = { workspace = true }
humantime = { workspace = true }
maestro   = { workspace = true }
redis     = { workspace = true, features = ["streams", "tokio-comp"] }
shared    = { workspace = true }
tc-client = { workspace = true }
tokio     = { workspace = true }
tracing   = { workspace = true }


[dev-dependencies]
mockall    = { workspace = true }
test-utils = { workspace = true }
[lints]
workspace = true
