[package]
name = "types"
version.workspace = true
description = "Types for the metabased-translator"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy = { version = "0.9.2", features = ["full"] }
pre-commit-hooks = "0.3.0"
strum = "0.26.3"
strum_macros = "0.26.4"


[dev-dependencies]
test-case = "3"
serial_test = "3.2.0"


[lints]
workspace = true
