[package]
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "synd-tee-attestation-zk-proofs-aws-nitro"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
alloy      = { workspace = true, features = ["sol-types"] }
const-oid  = { workspace = true, features = ["db"] }
p384       = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_cbor = { workspace = true, default-features = true }
x509-cert  = { workspace = true }


[dev-dependencies]
alloy = { workspace = true }
