[package]
edition.workspace    = true
exclude.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "synd-tee-attestation-zk-proofs-aws-nitro"
repository.workspace = true
version.workspace    = true

[dependencies]
alloy-primitives = { workspace = true }
p384             = { workspace = true, features = ["ecdsa", "pkcs8"] }
serde            = { workspace = true, features = ["derive"] }
serde_bytes      = { workspace = true }
serde_cbor       = { workspace = true, features = ["alloc"] }
x509-cert        = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]

[dev-dependencies]
hex = { workspace = true }

[features]
std = ["serde_cbor/std"]
