[package]
edition.workspace    = true
exclude.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "synd-tee-attestation-zk-proofs-aws-nitro"
repository.workspace = true
version.workspace    = true

[dependencies]
alloy-primitives = { workspace = true }
openvm-keccak256 = { workspace = true, optional = true }
openvm-p384      = { workspace = true, features = ["ecdsa", "pkcs8", "sha384"], optional = true }
# p384 is unused when the openvm feature is enabled as openvm-p384 is used instead
p384        = { workspace = true, features = ["ecdsa", "pkcs8"] }
serde       = { workspace = true, features = ["derive"] }
serde_bytes = { workspace = true }
serde_cbor  = { workspace = true, features = ["alloc"] }
x509-cert   = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]

[dev-dependencies]
hex = { workspace = true }

[features]
openvm = ["dep:openvm-keccak256", "dep:openvm-p384"]
std    = ["serde_cbor/std"]
