services:
  mchain:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-mchain:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-mchain
    #   dockerfile: Dockerfile
    environment:
      APPCHAIN_CHAIN_ID: ${APPCHAIN_CHAIN_ID}
    ports:
      - "8545"
      - "8546"
    volumes:
      - ./datadir:/datadir
    networks:
      - appchains-network

  seq-ingestor:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-chain-ingestor:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-chain-ingestor
    #   dockerfile: Dockerfile
    volumes:
      - ./:/chains
    environment:
      DB_FILE: /chains/ingestor.db
      START_BLOCK: 0
      WS_URLS: ${SEQUENCING_WS_URLS}
    ports:
      - "8545"
      - "8546"
    networks:
      - appchains-network

  set-ingestor:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-chain-ingestor:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-chain-ingestor
    #   dockerfile: Dockerfile
    volumes:
      - ./:/chains
    environment:
      DB_FILE: /chains/ingestor.db
      START_BLOCK: 20000000
      WS_URLS: ${SETTLEMENT_WS_URLS}
    ports:
      - "8545"
      - "8546"
    networks:
      - appchains-network

  healthcheck:
    image: curlimages/curl:8.13.0
    healthcheck:
      test: curl -f http://mchain:8546/metrics && curl -f http://seq-ingestor:8546/metrics && curl -f http://set-ingestor:8546/metrics
      start_period: 3600s
    tty: true
    entrypoint: /bin/sh
    networks:
      - appchains-network

  translator:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-translator:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-translator
    #   dockerfile: Dockerfile
    environment:
      APPCHAIN_CHAIN_ID: ${APPCHAIN_CHAIN_ID}
      SEQUENCING_CONTRACT_ADDRESS: ${SEQUENCING_CONTRACT_ADDRESS}
      ARBITRUM_BRIDGE_ADDRESS: ${ARBITRUM_BRIDGE_ADDRESS}
      ARBITRUM_INBOX_ADDRESS: ${ARBITRUM_INBOX_ADDRESS}
      SEQUENCING_WS_URL: "ws://seq-ingestor:8545"
      SEQUENCING_START_BLOCK: ${SEQUENCING_START_BLOCK}
      SETTLEMENT_WS_URL: "ws://set-ingestor:8545"
      SETTLEMENT_START_BLOCK: ${SETTLEMENT_START_BLOCK}
      MCHAIN_WS_URL: "ws://mchain:8545"
      SETTLEMENT_DELAY: "60"
    depends_on:
      healthcheck:
        condition: service_healthy
    networks:
      - appchains-network

  nitro:
    image: ghcr.io/syndicateprotocol/nitro/nitro:eigenda-v3.6.4-rc.2
    command:
      - "--parent-chain.connection.url=ws://mchain:8545"
      - "--http.api=arb,eth,net,web3,txpool,arbtrace,synd"
      - "--node.dangerous.disable-blob-reader=true"
      - "--node.inbox-reader.check-delay=100ms"
      - "--node.staker.enable=false"
      - "--node.parent-chain-reader.poll-interval=100ms"
      - "--node.parent-chain-reader.old-header-timeout=2540400h"
      - "--execution.parent-chain-reader.old-header-timeout=2540400h"
      - "--execution.caching.archive=true"
      - "--ensure-rollup-deployment=false"
      - "--chain.info-files=/config/chain_info.json"
      - "--metrics"
      - "--log-level=error"    
    depends_on:
      healthcheck:
        condition: service_healthy
    volumes:
      - ./config:/cfg:ro
      - ./data:/home/user/.arbitrum
    ports:
      - "8547"
      - "6070"
    networks:
      - appchains-network

networks:
  appchains-network:
    driver: bridge
