services:
  mchain:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-mchain:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-mchain
    #   dockerfile: Dockerfile
    environment:
      APPCHAIN_CHAIN_ID: ${APPCHAIN_CHAIN_ID}
    ports:
      - 5555:8545

  seq-ingestor:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-chain-ingestor:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-chain-ingestor
    #   dockerfile: Dockerfile
    volumes:
      - ./:/chains
    environment:
      - DB_FILE=/chains/${SEQUENCING_CHAIN_ID}.db
      - START_BLOCK=0
      - WS_URLS=${SEQUENCING_WS_URL}

  set-ingestor:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-chain-ingestor:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-chain-ingestor
    #   dockerfile: Dockerfile
    volumes:
      - ./:/chains
    environment:
      - DB_FILE=/chains/84532.db
      - START_BLOCK=20000000
      - WS_URLS=${SETTLEMENT_WS_URL}

  healthcheck:
    image: curlimages/curl:8.13.0
    healthcheck:
      test: curl -f http://mchain:8546/metrics && curl -f http://seq-ingestor:8546/metrics && curl -f http://set-ingestor:8546/metrics
      start_period: 3600s
    tty: true
    entrypoint: /bin/sh

  translator:
    image: ghcr.io/syndicateprotocol/syndicate-appchains/synd-translator:latest
    platform: linux/amd64
    # build:
    #   context: ../../
    #   target: synd-translator
    #   dockerfile: Dockerfile
    environment:
      APPCHAIN_CHAIN_ID: ${APPCHAIN_CHAIN_ID}
      SEQUENCING_CONTRACT_ADDRESS: ${SEQUENCING_CONTRACT_ADDRESS}
      ARBITRUM_BRIDGE_ADDRESS: ${ARBITRUM_BRIDGE_ADDRESS}
      ARBITRUM_INBOX_ADDRESS: ${ARBITRUM_INBOX_ADDRESS}
      SEQUENCING_WS_URL: "ws://seq-ingestor:8545"
      SEQUENCING_START_BLOCK: ${SEQUENCING_START_BLOCK}
      SETTLEMENT_WS_URL: "ws://set-ingestor:8545"
      SETTLEMENT_START_BLOCK: ${SETTLEMENT_START_BLOCK}
      MCHAIN_WS_URL: "ws://mchain:8545"
      SETTLEMENT_DELAY: "60"
    depends_on:
      healthcheck:
        condition: service_healthy

  # nitro:
  #   image: offchainlabs/nitro-node:v3.6.2-5b41a2d-slim
  #   command: "--parent-chain.connection.url=ws://mchain:8545 --http.port=8545 --http.addr=0.0.0.0 --node.dangerous.disable-blob-reader --execution.forwarding-target=null --node.inbox-reader.check-delay=100ms --node.staker.enable=false --ensure-rollup-deployment=false --chain.info-files=/cfg/${CHAIN_INFO_FILE}"
  #   depends_on:
  #     healthcheck:
  #       condition: service_healthy
  #   volumes:
  #     - ./config:/cfg:ro
  #   ports:
  #     - 8545:8545
