# Add Foundry's bin directory to the PATH for all recipes
export PATH := env_var('PATH') + ":" + env_var('HOME') + "/.foundry/bin"

# Clone the Optimism repository
clone:
    git clone https://github.com/ethereum-optimism/optimism.git ~/optimism

# Install Foundry
install-foundry:
    #!/bin/bash
    set -e
    cd ~/optimism
    if ! just install-foundry; then
        echo "First install-foundry attempt failed. Sourcing .bashrc and trying again."
        source ~/.bashrc
        just install-foundry
    else
        echo "install-foundry succeeded on first attempt."
    fi
    source ~/.bashrc

# Initialize op-devnet
op-devnet-up:
    make --directory ~/optimism op-devnet-up
    @echo "OP Devnet initialized"

# Shut down devnet
op-devnet-down:
    make --directory ~/optimism op-devnet-down
    @echo "OP Devnet shut down"

# Run all steps in sequence
# OP Devnet setup based on https://docs.optimism.io/chain/testing/dev-node
all: clone install-foundry op-devnet-up op-devnet-down copy-justfile
    @echo "Post-create script completed successfully"

# Copy Justfile to ~/Metabased.justfile
# This gives easy access to op-devnet commands after the container is created
copy-justfile:
    cp {{justfile()}} ~/metabased-devnet.justfile
    @echo "Justfile copied to ~/metabased-devnet.justfile"
