[package]
name = "common"
version.workspace = true
description = "Common utilities for metabased-translator."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 
pre-commit-hooks = "0.3.0"

[lints]
workspace = true
