[package]
name = "common"
version.workspace = true
description = "Common utilities for metabased-translator, including types."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
alloy = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing = { workspace = true, features = ["attributes"] }

[dev-dependencies]
serial_test = { workspace = true }

[lints]
workspace = true
