[package]
description            = "Metrics for synd-translator."
edition.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "metrics"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true


[dependencies]
axum              = { workspace = true }
prometheus-client = { workspace = true }
reqwest           = { workspace = true }
shared            = { workspace = true }
synd-slotter      = { workspace = true }
tokio             = { workspace = true }

[lints]
workspace = true
