[package]
edition.workspace    = true
exclude.workspace    = true
homepage.workspace   = true
license.workspace    = true
name                 = "synd-tee-attestation-zk-proofs-sp1-program"
repository.workspace = true
version.workspace    = true

# pinned because of sp1 toolchain
rust-version = "1.85"


[dependencies]
alloy                                    = { workspace = true, features = ["sol-types"] }
sp1-zkvm                                 = { workspace = true }
synd-tee-attestation-zk-proofs-aws-nitro = { workspace = true }
