[package]
name = "block-builder"
version.workspace = true
description = "Block builder for metabased-translator."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy = { version = "0.9.2", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.128"
alloy-provider = { version = "0.9.2", features = ["default", "anvil-node"] }
alloy-primitives = "0.8.15"
alloy-rlp = "0.3.10"
flate2 = "1.0.35"
reqwest = "0.12.9"
hex = "0.4.3"
scopeguard = "1.2.0"
alloy-contract = "0.9.2"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = { version = "0.1.41", features = ["log"] }
alloy-rpc-types = "0.9.2"
alloy-network = "0.9.2"
alloy-node-bindings = "0.9.2"
pre-commit-hooks = "0.3.0"
clap = { version = "4.5.23", features = ["derive", "env"] }
async-trait = "0.1.85"

[dev-dependencies]
test-case = "3"
serial_test = "3.2.0"


[lints]
workspace = true
