[package]
description            = "Block builder for metabased-translator."
edition.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "block-builder"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
alloy = { workspace = true, features = [
  "contract",
  "node-bindings",
  "providers",
  "rlp",
  "rpc-types",
  "rpc-types-anvil",
  "signer-local",
  "signers",
  "sol-types",
] }
async-trait = { workspace = true }
base64 = { workspace = true }
brotli = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
common = { workspace = true }
contract-bindings = { workspace = true }
eyre = { workspace = true }
flate2 = { workspace = true }
hex = { workspace = true }
prometheus-client = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process", "rt-multi-thread"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
serial_test    = { workspace = true }
test-utils     = { workspace = true }
tracing-test   = { workspace = true }

[lints]
workspace = true
