[package]
name = "block-builder"
version.workspace = true
description = "Block builder for metabased-translator."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy = { workspace = true, features = [
  "providers",
  "node-bindings",
  "rpc-types",
  "rpc-types-anvil",
  "sol-types",
  "rlp",
  "contract",
  "signers",
  "signer-local",
] }
common = { workspace = true }
contract-bindings = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "process"] }
serde = { workspace = true }
serde_json = { workspace = true }
flate2 = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true, features = ["env", "derive"] }
base64 = { workspace = true }
brotli = { workspace = true }
hex = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
prometheus-client = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
assert_matches = { workspace = true }
tracing-test = { workspace = true }

[lints]
workspace = true
