[package]
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "shared"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[dependencies]
alloy = { workspace = true, features = [
  "consensus",
  "contract",
  "json-rpc",
  "k256",
  "providers",
  "reqwest",
  "rlp",
  "rpc-types",
  "signer-local",
  "signers",
] }

arc-swap                           = { workspace = true }
async-trait                        = { workspace = true }
axum                               = { workspace = true }
byte-unit                          = { workspace = true, features = ["default"] }
bytes                              = { workspace = true }
eyre                               = { workspace = true }
flate2                             = { workspace = true }
http                               = { workspace = true }
jsonrpsee                          = { workspace = true, features = ["client", "jsonrpsee-types"] }
opentelemetry                      = { workspace = true }
opentelemetry-otlp                 = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-stdout               = { workspace = true }
opentelemetry_sdk                  = { workspace = true }
prometheus-client                  = { workspace = true }
redis                              = { workspace = true, features = ["connection-manager", "tokio-comp"] }
rlp                                = { workspace = true }
serde                              = { workspace = true, features = ["derive"] }
serde_json                         = { workspace = true }
thiserror                          = { workspace = true }
tokio                              = { workspace = true }
tracing                            = { workspace = true }
tracing-opentelemetry              = { workspace = true }
tracing-subscriber                 = { workspace = true, features = ["env-filter", "json"] }
url                                = { workspace = true }


[lints]
workspace = true
