[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[rpc_endpoints]
localhost = "http://localhost:8545"
base_sepolia = "https://sepolia.base.org"
syndicate_frame = "https://rpc-frame.syndicate.io"
holesky = "https://ethereum-holesky-rpc.publicnode.com"
exo = "https://syndicate-exo.g.alchemy.com/public"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
