# Deploys an image to Cloud Run that already exists as part of a separate workflow
steps:
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-sequencer"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "metabased-sequencer-internal"  # Cloud Run service name
      - "--image"
      - "us-central1-docker.pkg.dev/metabased-testnet/images/metabased-rollup/metabased-sequencer:latest"
      - "--region"
      - "europe-west6"
      - "--service-account"
      - "cloud-run-service-account@metabased-testnet.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
