[package]
name = "metabased-translator"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.8", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.128"
alloy-provider = { version = "0.8.1", features = ["default", "anvil-node"] }
