services:
  reth:
    image: ghcr.io/syndicateprotocol/reth:1.0.0
    volumes:
      - .:/cfg:ro
      - ipc:/ipc
    command: "node --http --http.addr=0.0.0.0 --http.port=8050 --ipcpath=/ipc/reth.ipc --auth-ipc --auth-ipc.path=/ipc/auth.ipc --chain=/cfg/genesis.json"
  translator:
    build:
      context: ../../
      target: metabased-translator-debug
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=debug
      - MCHAIN_AUTH_IPC_PATH=/ipc/auth.ipc
      - MCHAIN_IPC_PATH=/ipc/reth.ipc
      - TARGET_CHAIN_ID=63821
      - SEQUENCING_CONTRACT_ADDRESS=0x536EA7C009ebE418501a1DB133b281a4a01d50f5
      - ARBITRUM_BRIDGE_ADDRESS=0x9682E8DFfdadA5C5834ea0c905543798C72690F2
      - ARBITRUM_INBOX_ADDRESS=0x5573d100711322FA0B28923A0786Cec221bb2e67
      - SEQUENCING_RPC_URL=REPLACE_ME
      - SEQUENCING_START_BLOCK=422342
      - SETTLEMENT_RPC_URL=REPLACE_ME
      - SETTLEMENT_START_BLOCK=22074164

    volumes:
      - ipc:/ipc
      - ./heaptrack_output:/heaptrack_output
    # Run the translator through heaptrack
    entrypoint: []
    command: sh -c "mkdir -p /heaptrack_output && heaptrack -o /heaptrack_output/translator /usr/local/bin/metabased-translator"
    depends_on:
      - reth
  nitro:
    image: offchainlabs/nitro-node:v3.4.0-d896e9c-slim
    command: "--parent-chain.connection.url=http://reth:8050 --node.dangerous.disable-blob-reader --execution.forwarding-target=null --node.inbox-reader.check-delay=100ms --node.staker.enable=false --ensure-rollup-deployment=false --chain.info-files=/cfg/chain_info.json"
    depends_on:
      - translator
    volumes:
      - .:/cfg:ro
volumes:
  ipc:
  heaptrack_output:
