services:
  reth:
    image: ghcr.io/syndicateprotocol/reth
    volumes:
      - .:/cfg:ro
      - ipc:/ipc
    command: "node --http --http.addr=0.0.0.0 --http.port=8050 --ipcpath=/ipc/reth.ipc --auth-ipc --auth-ipc.path=/ipc/auth.ipc --chain=/cfg/genesis.json"
  translator:
    build:
      context: ../../
      target: metabased-translator
      dockerfile: Dockerfile
    environment:
      - MCHAIN_AUTH_IPC_PATH=/ipc/auth.ipc
      - MCHAIN_IPC_PATH=/ipc/reth.ipc
      - SEQUENCING_CONTRACT_ADDRESS=0x0000000000000000000000000000000000000001
      - ARBITRUM_BRIDGE_ADDRESS=0x0000000000000000000000000000000000000001
      - ARBITRUM_INBOX_ADDRESS=0x0000000000000000000000000000000000000001
      - SEQUENCING_RPC_URL=http://reth:8050
      - SEQUENCING_START_BLOCK=0
      - SETTLEMENT_RPC_URL=http://reth:8050
      - SETTLEMENT_START_BLOCK=0
    volumes:
      - ipc:/ipc
    depends_on:
      - reth
  nitro:
    image: offchainlabs/nitro-node:v3.4.0-d896e9c-slim
    command: "--parent-chain.connection.url=http://reth:8050 --node.dangerous.disable-blob-reader --execution.forwarding-target=null --node.inbox-reader.check-delay=100ms --node.staker.enable=false --ensure-rollup-deployment=false --chain.info-files=/cfg/chain_info.json"
    depends_on:
      - translator
    volumes:
      - .:/cfg:ro
volumes:
  ipc:
