services:
  mchain:
    build:
      context: ../../
      target: mchain
      dockerfile: Dockerfile
    command: "--chain-id 510000 --port 8050"
  translator:
    build:
      context: ../../
      target: metabased-translator
      dockerfile: Dockerfile
    environment:
      - SEQUENCING_CONTRACT_ADDRESS=0x536EA7C009ebE418501a1DB133b281a4a01d50f5
      - ARBITRUM_BRIDGE_ADDRESS=0x9682E8DFfdadA5C5834ea0c905543798C72690F2
      - ARBITRUM_INBOX_ADDRESS=0x5573d100711322FA0B28923A0786Cec221bb2e67
      - SEQUENCING_RPC_URL=https://syndicate-exo.g.alchemy.com/v2/nYkJi2K0LszDqj8jzWY-rMJmK9ugf0oF
      - SEQUENCING_START_BLOCK=422342
      - SETTLEMENT_RPC_URL=https://base-sepolia.g.alchemy.com/v2/nYkJi2K0LszDqj8jzWY-rMJmK9ugf0oF
      - SETTLEMENT_START_BLOCK=22074164
      - MCHAIN_RPC_URL=http://mchain:8050
    depends_on:
      - mchain
