name: Foundry Tests

on:
  # Run workflow on every push to main. This ensures that cross-service PRs that
  # depend on synd-contracts are tested.
  push:
    branches:
      - main
  # Only run on PRs that touch shared contracts
  pull_request:
    paths:
      - "synd-contracts/**"
      - "shared/arb-contracts/**"
      - "shared/contract-bindings/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci

jobs:
  contracts-check:
    strategy:
      # Enable fail-fast to stop the job immediately if any step fails
      # This helps catch issues early and prevents wasting CI resources
      fail-fast: true
      matrix:
        contract-dir: ["shared/arb-contracts", "synd-contracts"]

    name: ${{ matrix.contract-dir }} Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.contract-dir }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      # when generating the bindings:
      # --force flag to clear the cache and artifacts folder and recompile
      # -C to create bindings only for a specific directory

      - name: Check Rust contract bindings for shared contratcs
        if: matrix.contract-dir == 'shared/arb-contracts'
        run: |
          forge bind --alloy --force
          mv out/bindings/src/lib.rs out/bindings/src/mod.rs
          diff -r -q out/bindings/src ../contract-bindings/src/arbitrum || (echo "Error: Rust contract bindings are out of date. Please run 'make -C shared create-contract-bindings' to update them." && exit 1)

      - name: Check Rust contract bindings for synd-contracts
        if: matrix.contract-dir == 'synd-contracts'
        run: |
          forge bind --alloy --force -C ./sequencing-modules
          mv out/bindings/src/lib.rs out/bindings/src/mod.rs
          diff -r -q out/bindings/src ../shared/contract-bindings/src/synd || (echo "Error: Rust contract bindings are out of date. Please run 'make -C shared create-contract-bindings' to update them." && exit 1)
