name: Dev Container Tests

on:
  # Temporarily disabled while we work on the justfile refactor
  # pull_request:
  # branches: [ main ]

jobs:
  arb-test:
    name: Arbitrum Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Infra + Run Arbitrum L2 + Run Metabased Sequencer + Test transaction
        timeout-minutes: 15
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/syndicateprotocol/metabased-devcontainer
          imageTag: cache-pr-${{ github.event.pull_request.number }}
          # Enable caching
          push: always
          # Pull cached images from both main branch and PR branch
          cacheFrom: |
            ghcr.io/syndicateprotocol/metabased-devcontainer:cache-main
            ghcr.io/syndicateprotocol/metabased-devcontainer:cache-pr-${{ github.event.pull_request.number }}
          runCmd: |
            # Run all verifications
            just -f .devcontainer/justfile verify-all

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: /tmp/sequencer-setup.log
