name: Dev Container E2E Tests

on:
  # Run workflow on every push to main
  push:
    branches:
      - main
  # Run workflow on all PRs
  pull_request:

permissions:
  contents: read
  packages: read  # Allows pulling cached container images from GHCR

jobs:
  metabased-e2e-test:
    name: Metabased E2E Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Infra + Run Arbitrum L2 + Run Metabased Sequencer + Verify with test transaction
        timeout-minutes: 30
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/syndicateprotocol/metabased-devcontainer
          imageTag: cache-main
          push: never
          # Using cache from .github/workflows/devcontainer-main-update.yaml which builds and maintains the cache-main tag
          cacheFrom: |
            ghcr.io/syndicateprotocol/metabased-devcontainer:cache-main
          runCmd: |
            # Run all verifications
            just verify-all

      - name: Run Metabased Translator E2E Tests
        timeout-minutes: 30
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/syndicateprotocol/metabased-devcontainer
          imageTag: cache-main
          push: never
          cacheFrom: |
            ghcr.io/syndicateprotocol/metabased-devcontainer:cache-main
          runCmd: |
            # Run E2E tests within our Rust code
            just e2e-tests

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: /tmp/sequencer-setup.log
