name: Dev Container Update

on:
  push:
    branches: [main]

# If any later dev container updates are pushed, cancel the earlier jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Allow for package uploads to GCR
permissions:
  contents: read
  packages: write
  actions: write # Added to allow canceling redundant workflow runs

jobs:
  update-cache:
    name: Update Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/syndicateprotocol/metabased-devcontainer
          imageTag: cache-main
          push: always
