name: Go CI

on:
  push:
    branches:
      - main
    paths:
      - "synd-withdrawals/synd-enclave/**"
      - "synd-withdrawals/synd-proposer/**"
  pull_request:
    paths:
      - "synd-withdrawals/synd-enclave/**"
      - "synd-withdrawals/synd-proposer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  enclave-build:
    name: build enclave
    runs-on: shared-large-01
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull submodules
        run: |
          cd synd-withdrawals/synd-enclave && \
          git submodule update --init --recursive

      - name: Build enclave image
        run: |
          cd synd-withdrawals/synd-enclave
          docker build --target eif-bin .
          docker build --target local-dev .

  proposer-test:
    name: test synd-proposer
    runs-on: shared-large-01
    permissions:
      contents: read
      id-token: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test synd-proposer via docker buildx
        run: |
          docker buildx build \
            --target synd-proposer-test \
            --tag synd-proposer-test \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --platform linux/amd64 \
            .
