name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  enclave-build:
    name: build enclave
    runs-on: vip-large-01
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull submodules
        run: |
          cd synd-withdrawals && \
          git submodule update --init --recursive

      - name: Build enclave image
        run: |
          docker build -f synd-withdrawals/synd-enclave/Dockerfile .

  proposer-test:
    name: test synd-proposer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Run Go tests
        run: |
          cd synd-withdrawals/synd-proposer
          go test ./...
