name: Go CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  enclave-build:
    name: build enclave
    runs-on: shared-medium-01
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull submodules
        run: |
          cd synd-withdrawals/synd-enclave && \
          git submodule update --init --recursive

      - name: Build enclave image
        run: |
          cd synd-withdrawals/synd-enclave
          docker build --target eif-bin .
          docker build --target local-dev .

  proposer-test:
    name: test synd-proposer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Pull all submodules
        run: |
          git submodule update --init --recursive
          cd synd-withdrawals/synd-proposer
          git submodule update --init --recursive

      - name: Tidy & verify modules
        run: |
          cd synd-withdrawals/synd-proposer
          go mod tidy

      - name: Run Go tests
        run: |
          cd synd-withdrawals/synd-proposer
          go test ./...
