name: "Olympix Integrated Security"

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "synd-contracts/src/**/*.sol"
      - "synd-contracts/certora/specs/**/*.spec"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Olympix Integrated Security
        uses: olympix/integrated-security@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
        with:
          args: -f tree --no-incomplete-constructor-tests --no-unfuzzed-local-variables --no-missing-revert-reason-tests
