# This workflow runs Olympix, an automated security analysis tool for smart contracts.
# Olympix scans our Solidity code for common vulnerabilities and security issues every time we push changes or open a PR.
# https://www.olympix.ai/

name: "Olympix Integrated Security"

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "synd-contracts/src/**/*.sol"
      - "synd-contracts/certora/specs/**/*.spec"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Run Olympix checks but filter out the checks that do not apply to our contracts
      - name: Run Olympix Integrated Security
        uses: olympix/integrated-security@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
        with:
          args: -f tree --no-incomplete-constructor-tests --no-missing-revert-reason-tests
