name: Publish Release Binaries

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag version (e.g., v1.2.3, v0.10.15-dev.1)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build artifacts
    runs-on: shared-medium-01
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build synd-withdrawals/server
        run: |
          cd synd-withdrawals/server
          docker build --output=. .

      - name: Build eif.bin file
        run: |
          cd synd-withdrawals
          docker build --target eif-bin --output=out .

      - name: Build sp1-zk-proofs elf file
        run: |
          docker build -f synd-withdrawals/synd-tee-attestation-zk-proofs/sp1/Dockerfile . --output ./sp1-build --platform linux/amd64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: |
            synd-withdrawals/out/eif.bin
            synd-withdrawals/server/app/server
            sp1-build/elf-output/synd-tee-attestation-zk-proofs-sp1-program
          retention-days: 1

  publish-release:
    name: Attach binaries to GitHub release
    permissions:
      contents: write
    needs: build
    runs-on: shared-medium-01
    env:
      TAG_NAME: ${{ github.event.release.tag_name || inputs.tag_name }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-artifacts

      - name: Rename artifacts with version
        run: |
          mv synd-withdrawals/out/eif.bin eif-${{ env.TAG_NAME }}.bin
          mv synd-withdrawals/server/app/server server-${{ env.TAG_NAME }}.bin
          mv sp1-build/elf-output/synd-tee-attestation-zk-proofs-sp1-program sp1-zk-${{ env.TAG_NAME }}.elf

      - name: Attach binaries to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            eif-${{ env.TAG_NAME }}.bin
            server-${{ env.TAG_NAME }}.bin
            sp1-zk-${{ env.TAG_NAME }}.elf

  notify-failure:
    name: Notify on failure
    permissions: {}
    if: always() && (needs.build.result == 'failure' || needs.publish-release.result == 'failure')
    needs: [build, publish-release]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on Failure
        uses: rtCamp/action-slack-notify@v2
        with:
          status: failure
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          color: danger
          message: ":x: `${{github.workflow}}` failed. View failure information here: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>"
          title: "*${{github.workflow}}* failed"
