# This workflow runs on PRs to `main` to confirm that all Docker images will build successfully. It does not actually push the images to the registry.
# It does NOT publish the images anywhere.

name: Publish Service Images (Dry Run)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review] # the first 3 are the defaults if you dont specify `types`
    branches: [main, staging]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  docker:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/publish-images.yaml
    with:
      dry_run: true
      runner_label: shared-large-01
      service: "" # all services
    secrets: inherit
