# This workflow runs on PRs to `main` to confirm that all Docker images will build successfully. It does not actually push the images to the registry.
# It does NOT publish the images anywhere.

name: Publish Service Images (Dry Run)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/publish-images.yaml
    with:
      dry_run: false #TODO - change me back
      runner_label: shared-large-01
      service: "" # all services
      tags: '["SEQ-1151-test-n01", "SEQ-1151-test-n01-other-tag"]'
    secrets: inherit
