name: Build Proposer image - TODO
on:
  pull_request:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: shared-large-01
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build synd-proposer
        run: |
          docker build . -f synd-withdrawals/withdrawals.Dockerfile \
            -t synd-proposer:${{ github.sha }}