name: Build + Push Translator Image to Github and Google Registries
on:
  push:
#    TODO
#    branches:
#      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-core.yaml
    with:
      do_push: true
      target_name: metabased-translator
    secrets: inherit