# This workflow is run on every `main` PR and simply makes sure that our docker image builds succeed.
# It does not actually publish the images anywhere.

name: Publish Service Images (Dry Run)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/publish-images.yaml
    with:
      dry_run: true
      service: "" # all services
    secrets: inherit
