name: Build + Push Translator Image to Github and Google Registries
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-core.yaml
    with:
      do_push: true
      target_name: metabased-translator
      runner_label: vip-large-01
    secrets: inherit