# This workflow is run on every new release of the `Syndicate Appchains` stack. It builds and publishes all Docker images to our container registry.


name: Publish Release Images

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/publish-images.yaml
    with:
      dry_run: false
      runner_label: vip-large-01
      service: "" # all services
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit
