name: Publish Nitro Node Builder

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  docker:
    name: Build and Push Nitro Node Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower-case repo name
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Nitro Node Builder
        run: |
          cd synd-withdrawals/synd-enclave/nitro
          ORG_LOWER=$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')
          REPO_LOWER=$(echo "$GITHUB_REPOSITORY"       | tr '[:upper:]' '[:lower:]')
          docker buildx build --platform linux/amd64 -t ${{ env.GITHUB_REGISTRY }}/${REPO_LOWER}/node-builder:latest .
          docker push ${{ env.GITHUB_REGISTRY }}/${REPO_LOWER}/node-builder:latest
