name: Rust Tests metabased-sequencer

on:
  push:
    branches:
      - main
    # paths:
    # - "metabased-sequencer/**"
  pull_request:
    # paths:
    # - "metabased-sequencer/**"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: metabased-sequencer

jobs:
  test:
    name: Run Rust Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # GitHub Actions supports rustup by default, so we can install the toolchain directly
      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "metabased-sequencer -> target"

      - name: Run tests
        run: cargo test --all
