name: Rust Clippy Check

on:
  push:
    branches:
      - main
    # paths:
    # - "metabased-sequencer/**"
  pull_request:
    # paths:
    # - "metabased-sequencer/**"

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: metabased-sequencer
    steps:
      - uses: actions/checkout@v4

      - run: rustup component add clippy

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "metabased-sequencer -> target"

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
