name: Rust CI - Withdrawals

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review] # the first 3 are the defaults if you dont specify `types`
    branches:
      - main
  workflow_run:
    workflows: ["Publish Service Images"] # Run on `main` pushes only AFTER `publish-images` workflow completes successfully
    types:
      - completed
    branches:
      - main

jobs:
  withdrawal-tests:
    uses: ./.github/workflows/rust-ci-extra-test.yml
    with:
      test_name: "E2E Withdrawal Tests"
      monitored_paths: '["synd-withdrawals/", "synd-contracts/src/withdrawal/", "test-framework/tests/e2e/e2e_tests_withdrawals.rs", "shared/contract-bindings"]'
      test_filter: "test(e2e_tee_withdrawal)"
    secrets: inherit
