name: Rust CI - Migration

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review] # the first 3 are the defaults if you dont specify `types`
    branches:
      - main
      - staging
  workflow_run:
    workflows: ["Publish Service Images"] # Run on `main` pushes only AFTER `publish-images` workflow completes successfully
    types:
      - completed
    branches:
      - main
      - staging

jobs:
  migration-tests:
    uses: ./.github/workflows/rust-ci-long-test.yml
    with:
      test_name: "E2E Migration Tests"
      monitored_paths: '["synd-migration-cli/", "synd-mchain/", "test-framework/tests/e2e/e2e_tests_migration.rs"]'
      test_filter: "test(e2e_migration)"
    secrets: inherit
