name: Go OP Translator tests

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]
    # paths:
    # - "op-translator/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Defaults for the job
    defaults:
      run:
        working-directory: op-translator

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Run Unit Tests
        run: make test
